/**
 * Author: Savan Patel
 */

export const GET_ALL_FOOD_SERVICE_PROVIDER_IN_CITY = "GET ALL FOOD SERVICE PROVIDER IN CITY"
export const GET_FOOD_SERVICE_PROVIDER = "GET FOOD SERVICE PROVIDER"
export const GET_ALL_MEALS_FROM_PROVIDER = "GET ALL MEALS FROM PROVIDER";
export const GET_A_MEAL_FROM_ID = "GET MEAL FROM ID";