export const GET_ALL_USER_PENDING_REQUESTS = "GET ALL USER PENDING REQUESTS";
export const GET_SINGLE_PENDING_REQUEST = "GET SINGLE PENDING REQUEST";
export const GET_ALL_USERS = "GET ALL USERS";
export const SHOW_ALERT = "SHOW ALERT";
export const HIDE_ALERT = "HIDE ALERT";